
USE DB_T04301_DAN_VASQUES;

-- CRIANDO A TABELA DE CONTATOS
CREATE TABLE TB_CONTATOS (
	id_contato INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    telefone VARCHAR(20) NOT NULL
);

INSERT INTO TB_CONTATOS (nome, telefone)
VALUES ('FLAVIO', '(14) 98888-7777'),
	   ('DARLAN', '(31) 96666-5555'),
       ('cARLOS', '(41) 93333-2222');
       
-- CONSULTA A TABELA DE CONTATOS
SELECT * FROM TB_CONTATOS;

-- ALTERANDO A ESTRUTURA DE UMA TABELA
-- ATRAVES DO COMANDO ALTER TABLE
ALTER TABLE TB_CONTATOS
ADD COLUMN ativo INT DEFAULT 1 -- ADICIONADO NOVA COLUNA

INSERT INTO TB_CONTATOS (nome, telefone)
VALUES ('RICARDO', '(78) 95555-4444');

-- CONSULTA SO O NOME E TELEFONE
SELECT nome, telefone FROM TB_CONTATOS;

-- DAR APELIDO PRA CONSULTA PRA SAIDA DE RELATORIO
-- UTILIZANDO O ALIAS PARA APELIDO DE COLUNA
SELECT nome, telefone AS celular FROM TB_CONTATOS; -- MUDA-SE 'TELEFONE' POR 'CELULAR' PRA RELATORIO, MAS NAO A ESTRUTURA

-- APRESENTA TODA A ESTRUTURA/DESCRICAO DA TABELA
DESCRIBE TB_CONTATOS;

-- ALTERA A TABELA DE CONTATO MUDANDO O NOME DA COLUNA TELEFONE PARA CELULAR
ALTER TABLE TB_CONTATOS
CHANGE COLUMN telefone celular VARCHAR(20) NOT NULL;

-- DELETANDO/EXCLUINDO UMA COLUNA NA TABELA
ALTER TABLE TB_CONTATOS
DROP COLUMN ativo;
