--CRIANDO DB COM TRATAMENTO
CREATE DATABASE IF NOT EXISTS DB_AGENDA_TELEFONE

--ACESSANDO BD
USE DB_AGENDA_TELEFONE;

--CRIANDO A TABELA CONTATOS
CREATE TABLE TB_CONTATOS_AGENDA (
		nome_contato varchar(200) not null,
		telefone varchar(30) not null,
);

--CONSULTA A TABELA CRIADA
SELECT * FROM TB_CONTATOS_AGENDA;

--INSERIR DADOS NA TABELA
INSERT TO TB_CONTATOS_AGENDA (nome_contato, telefone)
VALUES('Jose', '(11) 98746-5236');
