USE DB_T04301_DAN_VASQUES;

-- CRIAR A TABELA DE ALUNOS
CREATE TABLE TB_ALUNOS_CARGA_DADOS (
nome VARCHAR(50),
idade INT);

-- CONSULTA A TABELADB_T04301_DAN_VASQUES
SELECT * FROM TB_ALUNOS_CARGA_DADOS;

-- REALIZANDO A CARGA DE DADOS NA TABELA
LOAD DATA LOCAL INFILE '/home/danvasquesc/Base_Pessoas_SQL.csv'
INTO TABLE TB_ALUNOS_CARGA_DADOS
FIELDS TERMINATED BY ';'
ENCLOSED BY '"' -- EX: "DAN"
LINES TERMINATED BY '\n'
IGNORE 1 ROWS; -- IGNORAR CABEÇALHO