USE DB_T04301_DAN_VASQUES;

-- TABELA GRUPOS
CREATE TABLE TB_AGENDA_GRUPO (
	id_grupo INT AUTO_INCREMENT PRIMARY KEY,
    nome_grupo VARCHAR(100) NOT NULL);

INSERT INTO TB_AGENDA_GRUPO (nome_grupo)
VALUES ('AMIGOS'),
	   ('FAMILIA'),
       ('TRABALHO');


-- TABELA CONTATOS
CREATE TABLE TB_AGENDA_CONTATO (
	id_contato INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    id_grupo_contato INT NOT NULL,
    foreign key (id_grupo_contato) 
    references TB_AGENDA_GRUPO(id_grupo));

INSERT INTO TB_AGENDA_CONTATO (nome, email,id_grupo_contato)
VALUES ('FLAVIO', 'flavio@email.com', 1),
	   ('DARLAN', 'darlan@email.com', 2),
       ('CARLOS', 'carlos@email.com', 3),
       ('AMANDA', 'amanda@email.com', 1);


-- TABELA TELEFONE
CREATE TABLE TB_AGENDA_TELEFONE (
	telefone VARCHAR(20) PRIMARY KEY,
    id_contato_telefone INT NOT NULL); -- AQUI SEM CHAVE ESTRANGEIRA PRA TREINAR ALTER POSTERIORMENTE

INSERT INTO TB_AGENDA_TELEFONE (telefone, id_contato_telefone)
VALUES ('(12) 99999-9999', 1),
	   ('(13) 98888-8888', 2);


-- CONSULTAROS REGISTROS
SELECT * FROM TB_AGENDA_GRUPO;
SELECT * FROM TB_AGENDA_CONTATO;
SELECT * FROM TB_AGENDA_TELEFONE;

-- ALTER TABLE PARA CRIAR UMA CHAVE ESTRANGEIRA
ALTER TABLE TB_AGENDA_TELEFONE
ADD CONSTRAINT TB_AGENDA_TELEFONE_FK -- CONSTRAINT SERIA CHAVE ESTRANGEIRA
FOREIGN KEY (id_contato_telefone) 
REFERENCES TB_AGENDA_CONTATO(id_contato);

DESCRIBE TB_AGENDA_TELEFONE;
