-- PROPOSTA DE EXERCICIO PAPELARIA

-- CRIAR TABELAS

-- FORNECEDOR -> ID_FORNECEDOR, NOME, CNPJ, RESPONSAVEL
CREATE TABLE TB_FORNECEDOR_PAPELARIA (
	ID_FORNECEDOR INT auto_increment PRIMARY KEY,
    NOME_FORNECEDOR VARCHAR(200) NOT NULL,
    CNPJ VARCHAR(14) NOT NULL,
    RESPONSAVEL VARCHAR(100) NOT NULL
);

-- INSERIR REGISTROS NA TABELA DE PRODUTOS
INSERT INTO TB_FORNECEDOR_PAPELARIA (NOME_FORNECEDOR, CNPJ, RESPONSAVEL)
VALUES ('FABER CASTELL', '12345678901234', 'RONALDO'),
	   ('BIC', '98765432109876', 'LEILA');
       
-- CONSULTAR AS INFORMAÇÕES NA TABELA PRODUTOS
SELECT * FROM TB_FORNECEDOR_PAPELARIA;


-- PRODUTOS -> ID_PRODUTO, NOME_PRODUTO, ID_FORNECEDOR_PRODUTO
CREATE TABLE TB_PRODUTOS_PAPELARIA (
	ID_PRODUTO INT auto_increment PRIMARY KEY,
    NOME_PRODUTO VARCHAR(100) NOT NULL,
    ID_FORNECEDOR_PRODUTO INT NOT NULL,
    foreign key (ID_FORNECEDOR_PRODUTO) -- CHAVE ESTRANGEIRA
    references TB_FORNECEDOR_PAPELARIA(ID_FORNECEDOR)
);

-- INSERIR REGISTROS NA TABELA DE PRODUTOS
INSERT INTO TB_PRODUTOS_PAPELARIA (NOME_PRODUTO, ID_FORNECEDOR_PRODUTO)
VALUES ('LAPIS DE COLORIR', 1),
	   ('CANETA', 2);
       
-- CONSULTA A TABELA DE PRODUTOS
SELECT * FROM TB_PRODUTOS_PAPELARIA;

-- INSERIR NOVO REGISTRO DE UM FORNECEDOR QUE NAO EXISTE
INSERT INTO TB_PRODUTOS_PAPELARIA (NOME_PRODUTO, ID_FORNECEDOR_PRODUTO)
VALUES ('LAPISEIRA', 3); -- DA ERRO POIS NAO EXISTE FORNECEDOR 3

-- TENTANDO ELIMINAR UM FORNECEDOR QUE JA TEM PRODUTO ATRELADO
DELETE FROM TB_FORNECEDOR_PAPELARIA
WHERE ID_FORNECEDOR = 2; -- DA ERRO POIS EXISTE UM PRODUTO CADASTRADO E POR ISSO NAO PODE ELIMINAR TAL FORNECEDOR


-- VENDAS -> ID_VENDA, ID_PRODUTO_VENDA, DATA_VENDA, QTDE
CREATE TABLE TB_VENDAS_PAPELARIA (
	ID_VENDA INT auto_increment PRIMARY KEY,
    ID_PRODUTO_VENDA INT NOT NULL,
    DATA_VENDA DATE NOT NULL,
    QTDE INT NOT NULL,
    foreign key (ID_PRODUTO_VENDA)
    references TB_PRODUTOS_PAPELARIA(ID_PRODUTO)
);

-- INSERIR REGISTROS NA TABELA DE VENDAS
INSERT INTO TB_VENDAS_PAPELARIA (ID_PRODUTO_VENDA, DATA_VENDA, QTDE)
VALUES (1, '2026-06-12', 20),
	   (2, '2026-06-16', 30);
     
SELECT * FROM TB_VENDAS_PAPELARIA;